version: '3.8'

services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_PASSWORD}
    ports:
      - "9200:9200"
    env_file:
      - .env
    networks:
      - backend

  connexion-api:
    build: .
    container_name: connexion-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - opensearch
    networks:
      - backend

networks:
  backend:
    driver: bridge
