openapi: 3.0.0
info:
  title: Connexion OpenSearch API
  version: 1.0.0

paths:
  /tenants:
    get:
      summary: Get all tenants
      responses:
        "200":
          description: List of tenants
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    data:
                      type: string

  /anomaly_detection/{tenant_id}:
    get:
      summary: Get anomaly detection info for a tenant
      parameters:
        - name: tenant_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Anomaly detection info
          content:
            application/json:
              schema:
                type: object
                properties:
                  detector_id:
                    type: string
                  detector_name:
                    type: string
                  detector_description:
                    type: string
        "404":
          description: No anomaly detector found for this tenant
