apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: connexion-api
  name: connexion-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connexion-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: connexion-api
    spec:
      containers:
      - image: connexion-api:latest
        name: connexion-api
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: connexion-config
        - secretRef:
            name: opensearch-secret

        resources: {}
status: {}
