apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: opensearch
  name: opensearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: opensearch
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: opensearch
    spec:
      containers:
        - env:
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  key: DEBUG
                  name: env
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  key: HOST
                  name: env
            - name: OPENSEARCH_HOST
              valueFrom:
                configMapKeyRef:
                  key: OPENSEARCH_HOST
                  name: env
            - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: OPENSEARCH_INITIAL_ADMIN_PASSWORD
                  name: opensearch-secret
            - name: OPENSEARCH_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: OPENSEARCH_PASSWORD
                  name: env
            - name: OPENSEARCH_USER
              valueFrom:
                configMapKeyRef:
                  key: OPENSEARCH_USER
                  name: env
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: env
            - name: discovery.type
              value: single-node
          image: opensearchproject/opensearch:latest
          name: opensearch
          ports:
            - containerPort: 9200
              protocol: TCP
      restartPolicy: Always
